spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      # 使用alibaba的druid连接池、监控
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
         max-active: 10
         max-wait: 5000
         min-idle: 5
         initial-size: 2
         validation-query: SELECT 1
         test-on-borrow: false
         test-while-idle: true
         time-between-eviction-runs-millis: 18800
         web-stat-filter:
            enabled: true
            exclusions: js,gif,jpg,png,css,ico,/druid/*
         stat-view-servlet:
            enabled: true
            login-username: dream
            login-password: dream@2020

server:
   port: 9091
mybatis:
   config-location: classpath:mybatis-config.xml